---
- name: tests
  hosts: all
  gather_facts: no
  
  vars:
    vm_name: testing-vYOS-0

  vars_files:
    - .majikmike

  tasks:
    - name: Change user password in the guest machine
      community.vmware.vmware_vm_shell:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        folder: "/{{datacenter}}/vm"
        vm_id: "{{ vm_name }}"
        vm_username: vyos
        vm_password: vyos
        vm_shell: "source /opt/vyatta/etc/functions/script-template"
        vm_shell_args: "set system domain-name integrate.zone"
      delegate_to: localhost
