---
- name: ping
  connection: network_cli
  hosts: all

  vars:
    ansible_network_os: vyos
    ansible_user: vyos

  tasks:
    - name: Get config for VyOS devices
      vyos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
